In [5]:
import pandas as pd
import numpy as np

In [7]:
a = np.array([1,2,3])
#>>> np.reshape(a, 6)
#array([1, 2, 3, 4, 5, 6])
np.reshape(a, 3, order='C')
#array([1, 4, 2, 5, 3, 6])

array([1, 2, 3])

In [ ]:
import cv2
import numpy as np
# read image
path = "/Users/benjamin/Desktop/python.png"
img = cv2.imread(path)#, cv2.IMREAD_UNCHANGED)
#if img!=None:
cv2.imshow("Resized image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()
# # get dimensions of image
# dimensions = img.shape
 
# # height, width, number of channels in image
# height = img.shape[0]
# width = img.shape[1]
# channels = img.shape[2]
 
# print('Image Dimension    : ',dimensions)
# print('Image Height       : ',height)
# print('Image Width        : ',width)
# print('Number of Channels : ',channels)

In [ ]:
import cv2
import numpy as np

def process_inputs(input_image,height,width):
    img = cv2.imread(input_image)
    img = cv2.resize(img,(width,height))
    #img = img.transpose(1,3,height,width)
    img = np.transpose(img,(2,0,1))
    #img = img.transpose(2,0,1)
    #img = np.expand_dims(img, axis=0)
    img = np.reshape(img,(1,3,height,width))
    return img